### ISSUE TITLE
Failed to read the sensors: No data was read from sensor (Timeout)

### ISSUE THREAD

**Issue by ghost** [edorfaus/TEMPered#12]
Hi, i keep getting this error when running ./tempered.
A little backgroup.

lsusb shows
Bus 001 Device 004: 0c45:7402 TEMPerHUM Temperature & Humidity Sensor

./hid-query -e shows
/dev/hidraw0 : 0c45:7402 interface 0 : RDing TEMPer2HumiV1.1
/dev/hidraw1 : 0c45:7402 interface 1 : RDing TEMPer2HumiV1.1

sudo ./hid-query /dev/hidraw1 1 0x80 0x33 1
outputs..
Device /dev/hidraw1 : 0c45:7402 interface 1 : RDing TEMPer2Humiv1.1

Writing data (10 bytes):
00 01 80 33   01 00 00 00   00 00
No data was read from the drvice (timout)

Running sudo ./tempered outputs
/dev/hidraw1: Failed to read the sensors: No data was read from the sensor (Timeout)

Additional info: I'm running this on a Raspberry Pi running Raspbian Wheezy.

Any help getting this working would be a lifesaver.

**Comment by ghost** [comment]
Ok strangest thing, it's now working. All I had done was move to another part of the house! haha. Thanks for the great software.

**Comment by rountree** [comment]
This was the fifth program I looked at and the first one that worked.  Two observations:

1)  The CMake file is out of date wrt the hidlib project.  The directories containing the object files have changed.  
<code>
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 62c6d9a..02e93de 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -39,7 +39,7 @@ find_path(HIDAPI_HEADER_DIR hidapi.h
if (BUILD_HIDAPI_SHARED)
find_library(HIDAPI_LIB NAMES hidapi-hidraw hidapi-libusb
-PATHS ../hidapi ../hidapi.git
+PATHS ../hidapi/libusb/.libs
PATH_SUFFIXES linux libusb mac
DOC "The location of the HIDAPI shared library file"
)
</code>
2)  I kept getting a timeout error until I removed the Temper device and plugged it back in.

Hope that helps.

**Comment by fenderb** [comment]
I got this too, and re-inserting the USB device fixed it also, thanks!

**Comment by edorfaus** [comment]
Yeah, it's a known problem with these devices that it's very easy to cause them to lock up, so that you have to re-insert them to get them to work again. One wrong query, and it's locked up.

This caused me a bit of annoyance when I was experimenting with one of mine, trying to find all the queries that actually returned any info - I had hundreds of queries to try, and had to re-insert it after almost all of them. :(
(I kind of wanted to try more queries, actually, but didn't feel like re-inserting it the thousands of times required to try all of them. Maybe I'll rig up something to do the re-insertion automatically some day.)

As for the HIDAPI path change, thanks for mentioning it - I'll update my copy of the library and make sure it works.
