### ISSUE TITLE
Reading values from multiple devices

### ISSUE THREAD

**Issue by neptunix** [edorfaus/TEMPered#15]
Hi.
I've got three 0c45:7402 sensors. They all work fine except showing different values. They are all connected to the same usb-hub:

/dev/hidraw1 0: temperature 27.67 °C, relative humidity 45.4%, dew point 14.8 °C
/dev/hidraw5 0: temperature 26.92 °C, relative humidity 48.6%, dew point 15.2 °C
/dev/hidraw3 0: temperature 28.47 °C, relative humidity 46.9%, dew point 16.0 °C

This could be managed by calibration, but I'm not sure how can I distinguish them to set correct calibration values for each device.
Devices are being enumerated by the order they were plugged in.

Is there any way to get a unique value for each device - so that it will be no matter in which order i plug them (or reordering after a reboot)?

lsusb -v show equal information for every device.

**Comment by edorfaus** [comment]
As far as I know, there's no unique identifiers in these devices, unfortunately. It's something I've been annoyed about myself, actually, as it would have been nice to be able to know which was which of otherwise identical devices.

However, if you make sure to always plug them into the same port on your hub, it should be possible to use the USB path as a kind of identifier (at least as long as the hub allows you to see which port the devices are on - I'm not sure if that's universal), and then use the USB path to find the hidraw device (using udev or manually in /sys).

Actually, I'm not sure, but I think the libusb variant of HIDAPI actually uses the USB path as its identifier (instead of the /dev/hidrawN the hidraw variant uses), and if that's true and stable, you could use that instead of going from path to device yourself.
