### ISSUE TITLE
Need to use hidapi-libusb instead of hidapi-hidraw on my system (kernel 3.3.8)

### ISSUE THREAD

**Issue by ntolva** [edorfaus/TEMPered#16]
Hi,

This library only worked on my system after I edited CMakeLists.txt, line 41, and changed
"NAMES hidapi-hidraw hidapi-libusb" to "NAMES hidapi-libusb hidapi-hidraw".  I
have no idea why this fixed things, but I can dig more if it would help.

**Comment by edorfaus** [comment]
Well, that change basically just changes which variant of HIDAPI the build system looks for first, so that it defaults to the libusb variant instead of the hidraw variant if both are available and you don't specify which you want to use.

In other words, I think you could probably have gotten the same result by configuring the build to use the libusb variant, without having to change the CMakeLists.txt file - as there's a configuration setting for just that purpose. (I guess the configuration of the build system could use some more documentation though; after all, CMake is rather different from autoconf in that respect...)

I don't know why the hidraw variant wouldn't work for you, but as long as it works fine with the libusb variant, I guess it doesn't really matter that much...
